name = "ltl_formal_verification"
version = "0.1.0"
defaultTargets = ["ltl_formal_verification"]

[[lean_lib]]
name = "TuxedoMVC"

[[lean_exe]]
name = "ltl_formal_verification"
root = "Main"

[[lean_exe]]
name = "lean2wasm"
root = "Lean2Wasm"

[[lean_exe]]
name = "web_main"
root = "WebMain"
