name = "ltl_formal_verification"
version = "0.1.0"
defaultTargets = ["ltl_formal_verification"]

[[lean_lib]]
name = "LtlFormalVerification"

[[lean_exe]]
name = "ltl_formal_verification"
root = "Main"
